# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('active', models.NullBooleanField(default=True)),
                ('create_by', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pre-Planning'), ('A', 'Assignable'), ('I', 'In Progress'), ('H', 'Hold'), ('C', 'Completed'), ('X', 'Canceled')], default='P', max_length=1)),
                ('name', models.CharField(max_length=36)),
                ('assigned_to', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.Flows')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('Trigger', models.IntegerField()),
                ('name', models.CharField(max_length=36)),
                ('self_assign', models.NullBooleanField(default=False)),
                ('default_status', models.CharField(choices=[('P', 'Pre-Planning'), ('A', 'Assignable'), ('I', 'In Progress'), ('H', 'Hold'), ('C', 'Completed'), ('X', 'Canceled')], default='P', max_length=1)),
                ('fk_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.Flows')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('create_by', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('BA', 'Backlog'), ('RE', 'Requested'), ('AP', 'Approved'), ('DE', 'Denied'), ('IP', 'In Progress'), ('CX', 'Closed - Canceled'), ('CC', 'Closed - Complete')], default='DR', max_length=2)),
                ('fk_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.Flows')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='fk_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.TaskTemplates'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='fk_work_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.WorkRequests'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icarus.Roles'),
        ),
    ]
