# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0002_auto_20180114_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='fk_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Institutions'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fk_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Schools'),
        ),
        migrations.AlterField(
            model_name='courseversions',
            name='fk_bkstgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.BookstoreGroups'),
        ),
        migrations.AlterField(
            model_name='courseversions',
            name='fk_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Courses'),
        ),
        migrations.AlterField(
            model_name='flows',
            name='fk_PFCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.PFCat'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='fk_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Colleges'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='fk_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Flows'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='fk_task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.TaskTemplates'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Roles'),
        ),
        migrations.AlterField(
            model_name='tasktemplates',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Roles'),
        ),
        migrations.AlterField(
            model_name='workrequests',
            name='fk_courseversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.CourseVersions'),
        ),
        migrations.AlterField(
            model_name='workrequests',
            name='fk_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.Flows'),
        ),
        migrations.AlterField(
            model_name='workrequests',
            name='fk_work_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Icarus.WorkRequests'),
        ),
    ]
