# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0002_auto_20180103_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplates',
            name='phase',
            field=models.CharField(default='Not Set', max_length=36),
            preserve_default=False,
        ),
    ]
