# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0003_tasktemplates_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplates',
            name='phase',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
