# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0004_auto_20171209_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('BA', 'Backlog'), ('RE', 'Requested'), ('AP', 'Approved'), ('DE', 'Denied'), ('IP', 'In Progress'), ('CX', 'Closed - Canceled'), ('CC', 'Closed - Complete')], default='DR', max_length=2)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requestor', models.CharField(max_length=255)),
                ('PWA', models.CharField(max_length=255)),
                ('create_by', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workrequests',
            name='PWA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workrequests',
            name='proj_PWA',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workrequests',
            name='proj_requestor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workrequests',
            name='requestor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flows',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasktemplates',
            name='self_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workrequests',
            name='fk_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Icarus.Projects'),
        ),
    ]
