# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0004_auto_20180103_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workrequests',
            name='phase',
            field=models.CharField(default='Draft', max_length=255, null=True),
        ),
    ]
