# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0006_auto_20171216_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
