# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0007_auto_20171216_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='acronym',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='acronym',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roles',
            name='acronym',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schools',
            name='acronym',
            field=models.CharField(max_length=10),
        ),
    ]
