# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icarus', '0008_auto_20171216_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=10)),
                ('fk_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Icarus.Schools')),
            ],
        ),
        migrations.AddField(
            model_name='workrequests',
            name='fk_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Icarus.Courses'),
        ),
    ]
